[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
icb_core = "EpzmAas4F7XAWeHht7Yp3wTDcTciKLmXkhqaR5JhfCHE"
icb_reserve = "yiUCxoup6Jh7pcUsyZ8zR93kA13ecQX6EDdSEkGapQx"
icb_token = "9ABvYDxGzRErKe7Y4DECXJzLtKTeTabgkLjyTqv3P54j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/icb-core", "programs/icb-reserve", "programs/icb-token"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
