[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
ars_core = "EpzmAas4F7XAWeHht7Yp3wTDcTciKLmXkhqaR5JhfCHE"
ars_reserve = "yiUCxoup6Jh7pcUsyZ8zR93kA13ecQX6EDdSEkGapQx"
ars_token = "9ABvYDxGzRErKe7Y4DECXJzLtKTeTabgkLjyTqv3P54j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/ars-core", "programs/ars-reserve", "programs/ars-token"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
